name: Check PyPI deployment

on:
  workflow_run:
    workflows: ["Upload Python Package"]
    types:
      - completed

jobs:
  check_pypi:
    name: Check PyPI deployment
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container: precice/precice:nightly
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          path: micro-manager

      - name: Install Dependencies
        run: |
          apt-get -qq update
          apt-get -qq install python3-dev python3-venv git pkg-config

      - name: Install Micro Manager from PyPI
        timeout-minutes: 6
        working-directory: micro-manager
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install micro-manager-precice

      - name: Run python dummy
        timeout-minutes: 3
        working-directory: micro-manager
        run: |
          . .venv/bin/activate
          cd examples/
          micro-manager-precice micro-manager-python-config.json &
          python3 macro_dummy.py no_adaptivity
          ./clean-example.sh
