name: Run checks for markdown, links, and pre-commit
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - "*"
jobs:
  check_md:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Lint markdown files (markdownlint)
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: '.'

  check_links:
    name: Check links in markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check links in markdown files (markdown-link-check)
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          config-file: '.markdown-link-check-config.json'

  precommit:
    name: pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          check-latest: true
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run checks
        run: pre-commit run -a -v
      - name: Git status
        if: always()
        run: git status
      - name: Full diff
        if: always()
        run: git diff
