name: Test adaptivity functionality in serial
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - "*"
jobs:
  adaptivity_integration_tests:
    name: Adaptivity integration tests in serial
    runs-on: ubuntu-latest
    container: precice/precice:nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: micro-manager

      - name: Install dependencies
        working-directory: micro-manager
        run: |
          apt-get -qq update
          apt-get -qq install python3-dev pipx git pkg-config

      - name: Install Micro Manager
        working-directory: micro-manager
        run: pipx install .

      - name: Run integration test with local adaptivity
        timeout-minutes: 3
        working-directory: micro-manager/tests/integration/test_unit_cube
        run: |
          micro-manager-precice micro-manager-config-local-adaptivity.json &
          python3 unit_cube.py 2

      - name: Run integration test with global adaptivity
        timeout-minutes: 3
        working-directory: micro-manager/tests/integration/test_unit_cube
        run: |
          micro-manager-precice micro-manager-config-global-adaptivity.json &
          python3 unit_cube.py 2

  adaptivity_unit_tests_serial:
    name: Run adaptivity unit tests in serial
    runs-on: ubuntu-latest
    container: precice/precice:nightly
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: micro-manager

      - name: Install Dependencies
        working-directory: micro-manager
        run: |
          apt-get -qq update
          apt-get -qq install python3-dev pipx git pkg-config

      - name: Install Micro Manager
        working-directory: micro-manager
        run: pipx install .

      - name: Run unit tests
        working-directory: micro-manager/tests/unit
        run: python3 -m unittest test_adaptivity_serial.py
