name: Run macro-micro dummy in parallel
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:  
  run_macro_micro_dummy:
    name: Run macro-micro dummy in parallel
    runs-on: ubuntu-latest
    container: precice/precice
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2      

      - name: Install sudo for MPI
        run: |
          apt-get -qq update
          apt-get -qq install sudo

      - name: Use mpi4py
        uses: mpi4py/setup-mpi@v1

      - name: Add user precice
        run: useradd -m -s /bin/bash precice

      - name: Install Dependencies
        run: |
          su -c "apt-get -qq install python3-dev python3-pip git python-is-python3 pkg-config" precice
          su -c "python -m pip install --upgrade pip" precice
          su -c "pip install setuptools wheel twine"

      - name: Install micro-manager
        run: su -c "pip3 install --user ."

      - name: Run Python macro-micro dummy in parallel (variant 1)        
        timeout-minutes: 3
        run: |
          chown -R precice examples/
          cd examples/
          su -c "mpiexec -n 2 python3 python-dummy/run_micro_manager.py --config ../micro-manager-config-parallel-1.json & python3 macro_dummy.py" precice

      - name: Run Python macro-micro dummy in parallel (variant 2)
        timeout-minutes: 3
        run: |
          chown -R precice examples/
          cd examples/
          su -c "mpiexec -n 6 python3 python-dummy/run_micro_manager.py --config ../micro-manager-config-parallel-2.json & python3 macro_dummy.py" precice
