name: Run checks for markdown, links, and pre-commit
on:
  workflow_call:

jobs:
  check_links:
    name: Links
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Check links in markdown files (markdown-link-check)
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          config-file: '.markdown-link-check-config.json'

  precommit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: '3.10'
          check-latest: true
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run checks
        run: pre-commit run -a -v
      - name: Git status
        if: always()
        run: git status
      - name: Full diff
        if: always()
        run: git diff
